In [1]:
import numpy as np

In [2]:
a = [[1,2,3],[4,5,2]]
b = [[1],[2],[3]]

In [3]:
array1 = np.array(a)

In [4]:
array2 =np.array(b)

In [8]:
array1*array2 # element wise multiplication

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [9]:
array1 @ array2

array([[14],
       [20]])

In [13]:
array1.shape

(2, 3)

In [14]:
array2.shape

(3, 1)

In [15]:
type(array1)

numpy.ndarray

In [25]:
a = np.arange(1,101)

In [26]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
b = a.reshape(-10,10)

In [28]:
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [31]:
b = a.reshape(-1,5)

In [32]:
b

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [38]:
np.random.random((5,4))

array([[0.15238321, 0.94306014, 0.06716942, 0.42676538],
       [0.03614299, 0.81625048, 0.74260453, 0.51684537],
       [0.65317396, 0.41059436, 0.55240884, 0.42956755],
       [0.36894725, 0.88250035, 0.42552725, 0.73567047],
       [0.25781477, 0.75097906, 0.71301275, 0.00593956]])

In [41]:
a = np.random.random(1000)

In [42]:
np.median(a)

0.4742394840745417

In [43]:
a

array([1.73241604e-01, 3.91883241e-01, 3.73335402e-01, 4.53436401e-02,
       5.50563427e-01, 4.66552908e-01, 1.19390117e-01, 9.07271398e-02,
       5.60208356e-01, 7.26327522e-01, 9.43279112e-01, 9.45798209e-01,
       6.26270089e-01, 9.84876212e-02, 7.99242432e-02, 5.08729793e-01,
       2.44449674e-01, 5.54101877e-02, 5.20207843e-01, 6.02398346e-01,
       6.58725688e-01, 8.80897147e-02, 9.83047640e-01, 2.54414480e-01,
       5.11530200e-01, 8.03051559e-01, 8.08872990e-01, 9.09545767e-01,
       6.94616947e-01, 7.73632055e-02, 6.68024919e-01, 7.68562638e-01,
       2.17651548e-01, 7.68180038e-01, 8.26666476e-01, 7.22455903e-01,
       6.60254422e-01, 5.75650785e-01, 1.79125199e-01, 8.88393239e-01,
       6.91690087e-02, 9.62399698e-01, 1.24957234e-01, 8.69591158e-01,
       3.84553454e-01, 4.54026105e-01, 1.60173669e-01, 5.63241559e-01,
       7.47004889e-01, 4.26351830e-01, 5.13292787e-01, 8.90737407e-01,
       2.31252577e-01, 7.47804419e-01, 7.47820029e-01, 1.37125119e-01,
      

In [45]:
np.mean(a)

0.48065394678642037

In [47]:
import statistics as stat

In [48]:
print(dir(stat))

['Decimal', 'Fraction', 'StatisticsError', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_coerce', '_convert', '_counts', '_exact_ratio', '_fail_neg', '_find_lteq', '_find_rteq', '_isfinite', '_ss', '_sum', 'bisect_left', 'bisect_right', 'collections', 'groupby', 'harmonic_mean', 'math', 'mean', 'median', 'median_grouped', 'median_high', 'median_low', 'mode', 'numbers', 'pstdev', 'pvariance', 'stdev', 'variance']


dir(stat)

$$ \sum $$
$$ \beta $$

$$ \alpha $$

$$ \sigma $$

$$ lim_x{0} $$ 

 $$ \sqrt{x+y} $$
 

$$ \sigma^2  = \sum_{i=0}^N  \frac  {x - \bar x} {N}$$

In [55]:
stat.mean(a)

0.48065394678642037

In [56]:
stat.mode(a)

StatisticsError: no unique mode; found 1000 equally common values

In [57]:
import pandas as pd

In [59]:
df = pd.DataFrame(a,column= ["a","b","c","d","e"])

TypeError: __init__() got an unexpected keyword argument 'column'

In [60]:
random.randn(1000)

AttributeError: module 'random' has no attribute 'randn'

In [64]:
x = np.eye(5,dtype=int)

In [65]:
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [78]:
y = np.linspace(1,10,7,dtype=int)

In [79]:
print(y)

[ 1  2  4  5  7  8 10]


In [1]:
x = [1,2,3,4,5,6,7]

In [4]:
import numpy as np 
a = np.array(x)

In [5]:
a


array([1, 2, 3, 4, 5, 6, 7])

In [6]:
print(a)

[1 2 3 4 5 6 7]


In [8]:
print(a**2)

[ 1  4  9 16 25 36 49]


In [20]:
import math
pow(12,12)

8916100448256

In [ ]:
a = [1,2,3,4,5,6,7,8,9]
