In [4]:
import numpy as np 


In [5]:
a1 = [1,2,3,4,5,6,7,8]

In [6]:
a = np.array(a1)

In [7]:
a.size

8

In [8]:
a.shape

(8,)

In [9]:
a.ndim

1

In [10]:
a.dtype

dtype('int32')

In [11]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a1 = np.array(a)

In [13]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a = []

In [15]:
a

[]

In [16]:
l = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
    
    
]

In [17]:
a = np.array(l)

In [18]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
a[1::2,[0,2,]]

array([[ 5,  7],
       [13, 15]])

In [20]:
a[1::2,[0,2,3]]

array([[ 5,  7,  8],
       [13, 15, 16]])

In [21]:
a*a


array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [22]:
x = [1,2,3,4,5,6,7,8,9]
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
x[0:3]

[1, 2, 3]

In [29]:
x[1:101]

[2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
x[0:4:2]

[1, 3]

In [33]:
x[:5]

[1, 2, 3, 4, 5]

In [34]:
x[6:]

[7, 8, 9]

In [43]:
l =[ [ 
       [1,2,3,4],
       [3,4,2,7],
       [6,3,8,5],
       [9,2,7,4]
    ],
     [
       [6,3,3,9],
       [5,1,2,8],
       [9,4,6,2],
       [4,6,8,9]
    ],
     [ 
       [6,2,8,2],
       [8,3,4,6],
       [1,4,7,9],
       [4,6,7,2]
    ]
    
    
] 
    

In [44]:
type(l)

list

In [45]:
b = np.array(l)

In [46]:
b

array([[[1, 2, 3, 4],
        [3, 4, 2, 7],
        [6, 3, 8, 5],
        [9, 2, 7, 4]],

       [[6, 3, 3, 9],
        [5, 1, 2, 8],
        [9, 4, 6, 2],
        [4, 6, 8, 9]],

       [[6, 2, 8, 2],
        [8, 3, 4, 6],
        [1, 4, 7, 9],
        [4, 6, 7, 2]]])

In [47]:
b.dtype

dtype('int32')

In [49]:
b = np.array(l,dtype=np.float32)

In [50]:
b

array([[[1., 2., 3., 4.],
        [3., 4., 2., 7.],
        [6., 3., 8., 5.],
        [9., 2., 7., 4.]],

       [[6., 3., 3., 9.],
        [5., 1., 2., 8.],
        [9., 4., 6., 2.],
        [4., 6., 8., 9.]],

       [[6., 2., 8., 2.],
        [8., 3., 4., 6.],
        [1., 4., 7., 9.],
        [4., 6., 7., 2.]]], dtype=float32)

In [51]:
b = np.array(l,dtype=np.int32)

In [52]:
b

array([[[1, 2, 3, 4],
        [3, 4, 2, 7],
        [6, 3, 8, 5],
        [9, 2, 7, 4]],

       [[6, 3, 3, 9],
        [5, 1, 2, 8],
        [9, 4, 6, 2],
        [4, 6, 8, 9]],

       [[6, 2, 8, 2],
        [8, 3, 4, 6],
        [1, 4, 7, 9],
        [4, 6, 7, 2]]])

In [53]:
b.size

48

In [54]:
b.shape

(3, 4, 4)

In [67]:
b[0:1,[0,1]]

array([[[1, 2, 3, 4],
        [3, 4, 2, 7]]])

In [69]:
print(b[0:1,[0,1]])

[[[1 2 3 4]
  [3 4 2 7]]]


In [70]:
type(b)

numpy.ndarray

In [76]:
b

array([[[1, 2, 3, 4],
        [3, 4, 2, 7],
        [6, 3, 8, 5],
        [9, 2, 7, 4]],

       [[6, 3, 3, 9],
        [5, 1, 2, 8],
        [9, 4, 6, 2],
        [4, 6, 8, 9]],

       [[6, 2, 8, 2],
        [8, 3, 4, 6],
        [1, 4, 7, 9],
        [4, 6, 7, 2]]])

In [78]:
b[0:4:2,[0,1]]

array([[[1, 2, 3, 4],
        [3, 4, 2, 7]],

       [[6, 2, 8, 2],
        [8, 3, 4, 6]]])

In [79]:
b[0:3:2,[0,2,3]]

array([[[1, 2, 3, 4],
        [6, 3, 8, 5],
        [9, 2, 7, 4]],

       [[6, 2, 8, 2],
        [1, 4, 7, 9],
        [4, 6, 7, 2]]])

In [80]:
b

array([[[1, 2, 3, 4],
        [3, 4, 2, 7],
        [6, 3, 8, 5],
        [9, 2, 7, 4]],

       [[6, 3, 3, 9],
        [5, 1, 2, 8],
        [9, 4, 6, 2],
        [4, 6, 8, 9]],

       [[6, 2, 8, 2],
        [8, 3, 4, 6],
        [1, 4, 7, 9],
        [4, 6, 7, 2]]])