In [1]:
import numpy as np 


In [2]:
a1 = [1,2,3,4,5,6,7,8]

In [3]:
a = np.array(a1)

In [4]:
a.size

8

In [5]:
a.shape

(8,)

In [6]:
a.ndim

1

In [7]:
a.dtype

dtype('int32')

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a1 = np.array(a)

In [10]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
a = []

In [12]:
a

[]

In [13]:
l = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
    
    
]

In [14]:
a = np.array(l)

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
a[1::2,[0,2,]]

array([[ 5,  7],
       [13, 15]])